#ifndef KERNEL_DRIVERS_INTERNAL_UART_H
#define KERNEL_DRIVERS_INTERNAL_UART_H 1

#ifndef KERNEL_DRIVERS_UART_H
#error "Use this header while building uart only"
#endif

#define UART_DATA 0
#define UART_INTERRUPT 1
#define UART_INTERRUPT_IDENTIFACTOR 2
#define UART_LINE_CONTROL 3
#define UART_MODEM_CONTROL 4
#define UART_LINE_STATUS 5
#define UART_MODEM_STATUS 6
#define UART_SCRATCH 7

#define UART_BAUD_RATE_LOW UART_DATA
#define UART_BAUD_RATE_HIGH UART_INTERRUPT
#define UART_FIFO_CONTROLLER UART_INTERRUPT_IDENTIFACTOR

#define UART_LINE_DS_5 (0u)
#define UART_LINE_DS_6 (1u)
#define UART_LINE_DS_7 (2u)
#define UART_LINE_DS_8 (3u)
#define UART_LINE_DLAB_STATUS (1u << 7u)

#define UART_MODEM_DTR (1u << 0u)
#define UART_MODEM_RTS (1u << 1u)
#define UART_MODEM_OUT1 (1u << 2u)
#define UART_MODEM_OUT2 (1u << 3u)
#define UART_MODEM_LOOPBACK (1u << 4u)

#define UART_INTERRUPT_WHEN_DATA_AVAILABLE (1u << 0u)
#define UART_INTERRUPT_WHEN_TRANSMITTER_EMPTY (1u << 1u)
#define UART_INTERRUPT_WHEN_BREAK_EMPTY (1u << 2u)
#define UART_INTERRUPT_WHEN_STATUS_UPDATE (1u << 3u)

#define UART_LINE_DATA_READY (1u << 0u)
#define UART_LINE_OVERRUN_ERROR (1u << 1u)
#define UART_LINE_PARITY_ERROR (1u << 2u)
#define UART_LINE_FRAMING_ERROR (1u << 3u)
#define UART_LINE_BREAK_INDICATOR (1u << 4u)
#define UART_LINE_TRANSMITTER_BUF_EMPTY (1u << 5u)
#define UART_LINE_TRANSMITTER_EMPTY (1u << 6u)
#define UART_LINE_IMPENDING_ERROR (1u << 7u)

#define UART_ENABLE_FIFO (1u << 0u)
#define UART_FIFO_CLEAR_RECEIVE (1u << 1u)
#define UART_FIFO_CLEAR_TRANSMIT (1u << 2u)
#define UART_FIFO_ENABLE_64_BYTE (1u << 5u)
#define UART_FIFO_TRIGGER_LEVEL1 (0u << 6u)
#define UART_FIFO_TRIGGER_LEVEL2 (1u << 6u)
#define UART_FIFO_TRIGGER_LEVEL3 (2u << 6u)
#define UART_FIFO_TRIGGER_LEVEL4 (3u << 6u)

#endif// KERNEL_DRIVERS_INTERNAL_UART_H